spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DB_USER} # DB user
    password: ${DB_PASSWORD} # DB password
  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true
